/*
 * Copyright 2013 FlockSpring Inc. All rights reserved
 */
package com.flockspring.ui.model;

/**
 * Programs.java
 *
 * @author Justen L. Britain
 * @date Oct 27, 2013
 *
 */
public enum Programs
{
    INFANT_CARE,
    TODDLER_CARE,
    SUNDAY_SCHOOL,
    BIBLE_STUDY,
    ADULT_EDUCATION,
    SPIRITUAL_CLASSES,
    PRE_SCHOOL,
    PRIMARY_SCHOOL,
    SECONDARY_SCHOOL,
    GRADUATE_STUDIES,
    CHILDRENS_GROUPS,
    MIDDLE_SCHOOL_GROUP,
    HIGH_SCHOOL_GROUP,
    YOUNG_ADULT_GROUP,
    ADULT_GROUP,
    SENIOR_GROUP,
    MENS_GROUP,
    WOMENS_GROUP,
    CHIOR,
    DANCE,
    MUSIC_MINISTRY,
    DRAMA,
    CREATIVE_ARTS,
    MENTORSHIPT,
    SPROTS,
    SOCAIL_EVENTS,
    SMALL_GROUPS,
    SINGLES_GROUPS,
    PRAYER_GROUPS,
    HEALING_MINISTRY,
    PROPHETIC_MINISTRY,
    WORSHIP_MINISTRY,
    MEDITATION,
    PRE_MARITIAL_COUNSELING,
    COUPLES_COUNSELING,
    GENERAL_COUNSELING,
    DIVORCE_GRIEF_COUNSELING,
    ADDICTION_RECOVERY_COUNSELING,
    COMMUNITY_OUTREACH,
    FOOD_PANTRY_OUTREACH,
    FAMILY_OUTREACH,
    HOMELESS_OUTREACH,
    SOCIAL_JUSTICE_OUTREACH,
    EVANGELISM_OUTREACH,
    MISSION_OUTREACH;
}
