DROP TABLE IF EXISTS LANGUAGE;
CREATE TABLE LANGUAGE(
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ISO_LANG_CODE VARCHAR(27),
	ENGLISH_NAME VARCHAR(127),
	LOCALIZED_NAME VARCHAR(127)
) engine InnoDB;