DROP TABLE IF EXISTS COUNTRY_LANGUAGES;
CREATE TABLE COUNTRY_LANGUAGES(
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    LANGUAGE_ID BIGINT NOT NULL,
    COUNTRY_ID BIGINT NOT NULL
) engine InnoDB;