DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE ADDRESS(
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	STREET1 VARCHAR(75),
    STREET2 VARCHAR(75),
    CITY VARCHAR(75),
    POSTAL_CODE VARCHAR(75),
    STATE VARCHAR(127),
    COUNTRY VARCHAR(127),
    LONGITUDE INT,
    LATITUDE INT
) engine InnoDB;