DROP TABLE IF EXISTS GLOBAL_REGION;
CREATE TABLE GLOBAL_REGION(
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	PARENT_REGION_ID BIGINT,
	REGION_TYPE VARCHAR(75),
	ENGLISH_NAME VARCHAR(75),
  	LOCALIZED_NAME VARCHAR(75),
	ISO_ALPHA_3_CODE VARCHAR(4),
	ISO_ALPHA_2_CODE VARCHAR(3),
	DESC_TYPE VARCHAR(20)
) engine InnoDB;

INSERT INTO GLOBAL_REGION (ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, 'Continent', 'North America');
SET @CONTINENT_ID = LAST_INSERT_ID();

    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Antigua and Barbuda', '', 'ATG', 'AG');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Anguilla', '', 'AIA', 'AI');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Netherlands Antilles', '', 'ANT', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Aruba', '', 'ABW', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Barbados', '', 'BRB', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Saint-Barthélemy', '', 'BLM', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Bermuda', '', 'BMU', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Bonaire, Saint Eustatius and Saba', '', 'BES', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Bahamas', '', 'BHS', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Belize', '', 'BLZ', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Costa Rica', '', 'CRI', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Cuba', '', 'CUB', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Curacao', '', 'CUW', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Dominica', '', 'DMA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Dominican Republic', '', 'DOM', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Grenada', '', 'GRD', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Greenland', '', 'GRL', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Guadeloupe', '', 'GLP', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Guatemala', '', 'GTM', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Honduras', '', 'HND', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Haiti', '', 'HTI', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Jamaica', '', 'JAM', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Saint Kitts and Nevis', '', 'KNA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Cayman Islands', '', 'CYM', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Saint Lucia', '', 'LCA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Saint Martin', '', 'MAF', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Martinique', '', 'MTQ', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Montserrat', '', 'MSR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Nicaragua', '', 'NIC', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Panama', '', 'PAN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Saint Pierre and Miquelon', '', 'SPM', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Puerto Rico', '', 'PRI', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'El Salvador', '', 'SLV', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Sint Maarten', '', 'SXM', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Turks and Caicos Islands', '', 'TCA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'TrinIDad and Tobago', '', 'TTO', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Saint Vincent and the Grenadines', '', 'VCT', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'British Virgin Islands', '', 'VGB', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'U.S. Virgin Islands', '', 'VIR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'United States', '', 'USA', '');
    SET @COUNTRY_ID = LAST_INSERT_ID();
	
        INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, @COUNTRY_ID, 'Division', 'Northeastern United States');
        SET @DIVISION_ID = LAST_INSERT_ID();
		
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, @DIVISION_ID, 'REGION', 'New England');
            SET @REGION_ID = LAST_INSERT_ID();
			
                INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Connecticut', 'CT');
                INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Maine', 'ME');
                INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Massachusetts', 'MA');
                INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'New Hampshire', 'NH');
                INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Rhode Island', 'RI');
                INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Vermont', 'VT');
				
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, @DIVISION_ID, 'REGION', 'MIDdle Atlantic');
            SET @REGION_ID = LAST_INSERT_ID();
			
                INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'New Jersey', 'NJ');
                INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'New York', 'NY');
                INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Pennsylvania', 'PA');
		
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, @COUNTRY_ID, 'Division', 'MIDwestern United States');
    SET @DIVISION_ID = LAST_INSERT_ID();
    
        INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, @DIVISION_ID, 'REGION', 'East North Central');
        SET @REGION_ID = LAST_INSERT_ID();
			
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Illinois', 'IL');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Indiana', 'IN');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Michigan', 'MI');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Ohio', 'OH');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Wisconsin', 'WI');
				
        INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, @DIVISION_ID, 'REGION', 'West North Central');
        SET @REGION_ID = LAST_INSERT_ID();
			
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Iowa', 'IA');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Kansas', 'KS');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Minnesota', 'MN');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Missouri', 'MO');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Nebraska', 'NE');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'North Dakota', 'ND');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'South Dakota', 'SD');						
    
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, @COUNTRY_ID, 'Division', 'Western United States');
    SET @DIVISION_ID = LAST_INSERT_ID();

        INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, @DIVISION_ID, 'REGION', 'Pacific');
        SET @REGION_ID = LAST_INSERT_ID();
        
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Alaska', 'AK');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Hawaii', 'HI');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Oregon', 'OR');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Washington', 'WA');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Calinfornia', 'CA');
				
        INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, @DIVISION_ID, 'REGION', 'Northwest Mountain');
        SET @REGION_ID = LAST_INSERT_ID();
        
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'IDaho', 'ID');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Montana', 'MT');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Wyoming', 'WY');
				
        INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, @DIVISION_ID, 'REGION', 'Southwest Mountain');
        SET @REGION_ID = LAST_INSERT_ID();
			
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Arizona', 'AZ');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Colorado', 'CO');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'New Mexico', 'NM');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Nevada', 'NV');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Utah', 'UT');						
		
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, @COUNTRY_ID, 'Division', 'Southern United States');
    SET @DIVISION_ID = LAST_INSERT_ID();
    
        INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, @DIVISION_ID, 'REGION', 'West South Central');
        SET @REGION_ID = LAST_INSERT_ID();
			
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Arkansas', 'AR');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Louisiana', 'LA');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Oklahoma', 'OK');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Texas', 'TX');
            
        INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, @DIVISION_ID, 'REGION', 'East South Central');
        SET @REGION_ID = LAST_INSERT_ID();
        
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Alabama', 'AL');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Kentucky', 'KY');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Mississippi', 'MS');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Tennessee', 'TN');
            
        INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, @DIVISION_ID, 'REGION', 'South Atlantic');
        SET @REGION_ID = LAST_INSERT_ID();
			
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Deleware', 'DE');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'FlorIDa', 'FL');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Georgia', 'GA');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Maryland', 'MD');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'North Carolina', 'NC');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'South Carolina', 'SC');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Virginia', 'VA');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'West Virginia', 'WV');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Washington D.C.', 'DC');

    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Canada', '', 'CAN', 'CA');
    SET @COUNTRY_ID = LAST_INSERT_ID();

        INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, @COUNTRY_ID, 'REGION', 'Western Canada');
        SET @REGION_ID = LAST_INSERT_ID();
		
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Alberta', 'Alberta', 'AB');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'British Columbia', 'Colombie-Britannique', 'BC');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Manitoba', 'Manitoba', 'MB');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Saskatchewan', 'Saskatchewan', 'SK');
                    
        INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, @COUNTRY_ID, 'REGION', 'Central Canada');
        SET @REGION_ID = LAST_INSERT_ID();
		
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Ontario', 'Ontario', 'ON');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Quebec', 'Québec', 'QC');
			
        INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, @COUNTRY_ID, 'REGION', 'Eastern Canada');
        SET @REGION_ID = LAST_INSERT_ID();
		
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Newfoundland and Labrador', 'Terre-Neuve-et-Labrador', 'NL');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Nova Scotia', 'Nouvelle-Écosse', 'NS');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Prince Edward Island', 'Île-du-Prince-Édouard', 'PE');
			
        INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, @COUNTRY_ID, 'REGION', 'Northern Canada');
        SET @REGION_ID = LAST_INSERT_ID();
		
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Northwest Territories', 'Territoires du Nord-Ouest', 'NT');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Nunavut', 'Nunavut', 'NU');
            INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_2_CODE) VALUES (null, @REGION_ID, 'State', 'Yukon', 'Yukon', 'YT');		
        
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Mexico', '', 'MEX', 'MX');
  	
INSERT INTO GLOBAL_REGION (ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, 'Continent', 'Europe');
SET @CONTINENT_ID = LAST_INSERT_ID();

    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Andorra', '', 'AND', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Albania', '', 'ALB', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Austria', '', 'AUT', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Åland Islands', '', 'ALA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Bosnia and Herzegovina', '', 'BIH', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Belgium', '', 'BEL', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Bulgaria', '', 'BGR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Belarus', '', 'BLR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Switzerland', '', 'CHE', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Serbia and Montenegro', '', 'SCG', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Cyprus', '', 'CYP', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Czech Republic', '', 'CZE', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Germany', '', 'DEU', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Denmark', '', 'DNK', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Estonia', '', 'EST', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Spain', '', 'ESP', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Finland', '', 'FIN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Faroe Islands', '', 'FRO', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'France', '', 'FRA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'United Kingdom', '', 'GBR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Guernsey', '', 'GGY', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Gibraltar', '', 'GIB', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Greece', '', 'GRC', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Croatia', '', 'HRV', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Hungary', '', 'HUN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Ireland', '', 'IRL', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Isle of Man', '', 'IMN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Iceland', '', 'ISL', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Italy', '', 'ITA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Jersey', '', 'JEY', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Liechtenstein', '', 'LIE', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Lithuania', '', 'LTU', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Luxembourg', '', 'LUX', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Latvia', '', 'LVA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Monaco', '', 'MCO', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Moldova', '', 'MDA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Montenegro', '', 'MNE', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Macedonia', '', 'MKD', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Malta', '', 'MLT', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Netherlands', '', 'NLD', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Norway', '', 'NOR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Poland', '', 'POL', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Portugal', '', 'PRT', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Romania', '', 'ROU', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Serbia', '', 'SRB', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Russia', '', 'RUS', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Sweden', '', 'SWE', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Slovenia', '', 'SVN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Svalbard and Jan Mayen', '', 'SJM', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Slovakia', '', 'SVK', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'San Marino', '', 'SMR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Ukraine', '', 'UKR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Vatican City', '', 'VAT', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Kosovo', '', 'XKX', '');


INSERT INTO GLOBAL_REGION (ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, 'Continent', 'Australia');
SET @CONTINENT_ID = LAST_INSERT_ID();

    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'American Samoa', '', 'ASM', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Australia', '', 'AUS', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Cook Islands', '', 'COK', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Fiji', '', 'FJI', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Micronesia', '', 'FSM', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Guam', '', 'GUM', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Kiribati', '', 'KIR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Marshall Islands', '', 'MHL', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Northern Mariana Islands', '', 'MNP', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'New Caledonia', '', 'NCL', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Norfolk Island', '', 'NFK', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Nauru', '', 'NRU', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Niue', '', 'NIU', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'New Zealand', '', 'NZL', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'French Polynesia', '', 'PYF', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Papua New Guinea', '', 'PNG', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Pitcairn Islands', '', 'PCN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Palau', '', 'PLW', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Solomon Islands', '', 'SLB', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Tokelau', '', 'TKL', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'East Timor', '', 'TLS', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Tonga', '', 'TON', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Tuvalu', '', 'TUV', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'U.S. Minor Outlying Islands', '', 'UMI', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Vanuatu', '', 'VUT', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Wallis and Futuna', '', 'WLF', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Samoa', '', 'WSM', '');

INSERT INTO GLOBAL_REGION (ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, 'Continent', 'South America');
SET @CONTINENT_ID = LAST_INSERT_ID();

    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Argentina', '', 'ARG', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Bolivia', '', 'BOL', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Brazil', '', 'BRA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Chile', '', 'CHL', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Colombia', '', 'COL', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Ecuador', '', 'ECU', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Falkland Islands', '', 'FLK', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'French Guiana', '', 'GUF', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Guyana', '', 'GUY', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Peru', '', 'PER', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Paraguay', '', 'PRY', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'SuriNAME', '', 'SUR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Uruguay', '', 'URY', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @CONTINENT_ID, 'Country', 'Venezuela', '', 'VEN', '');

INSERT INTO GLOBAL_REGION (ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, 'Continent', 'Africa');
SET @CONTINENT_ID = LAST_INSERT_ID();
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Angola', '', 'AGO', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Burkina Faso', '', 'BFA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Burundi', '', 'BDI', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Benin', '', 'BEN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Botswana', '', 'BWA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Congo [DRC]', '', 'COD', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Central African Republic', '', 'CAF', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Congo [Republic]', '', 'COG', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Ivory Coast', '', 'CIV', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Cameroon', '', 'CMR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Cape Verde', '', 'CPV', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Djibouti', '', 'DJI', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Algeria', '', 'DZA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Egypt', '', 'EGY', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Western Sahara', '', 'ESH', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Eritrea', '', 'ERI', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Ethiopia', '', 'ETH', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Gabon', '', 'GAB', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Ghana', '', 'GHA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Gambia', '', 'GMB', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Guinea', '', 'GIN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Equatorial Guinea', '', 'GNQ', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Guinea-Bissau', '', 'GNB', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Kenya', '', 'KEN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Comoros', '', 'COM', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Liberia', '', 'LBR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Lesotho', '', 'LSO', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Libya', '', 'LBY', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Morocco', '', 'MAR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Madagascar', '', 'MDG', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Mali', '', 'MLI', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Mauritania', '', 'MRT', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Mauritius', '', 'MUS', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Malawi', '', 'MWI', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Mozambique', '', 'MOZ', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Namibia', '', 'NAM', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Niger', '', 'NER', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Nigeria', '', 'NGA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Réunion', '', 'REU', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Rwanda', '', 'RWA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Seychelles', '', 'SYC', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Sudan', '', 'SDN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Saint Helena', '', 'SHN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Sierra Leone', '', 'SLE', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Senegal', '', 'SEN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Somalia', '', 'SOM', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'South Sudan', '', 'SSD', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'São Tomé and Príncipe', '', 'STP', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Swaziland', '', 'SWZ', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Chad', '', 'TCD', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Togo', '', 'TGO', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Tunisia', '', 'TUN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Tanzania', '', 'TZA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Uganda', '', 'UGA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Mayotte', '', 'MYT', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'South Africa', '', 'ZAF', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Zambia', '', 'ZMB', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, ENGLISH_NAME, LOCALIZED_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Zimbabwe', '', 'ZWE', '');

INSERT INTO GLOBAL_REGION (ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, 'Continent', 'Asia');
SET @CONTINENT_ID = LAST_INSERT_ID();

    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'United Arab Emirates', '', 'ARE', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Afghanistan', '', 'AFG', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Armenia', '', 'ARM', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Azerbaijan', '', 'AZE', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Bangladesh', '', 'BGD', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Bahrain', '', 'BHR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Brunei', '', 'BRN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Bhutan', '', 'BTN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Cocos [Keeling] Islands', '', 'CCK', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'China', '', 'CHN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Christmas Island', '', 'CXR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Georgia', '', 'GEO', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Hong Kong', '', 'HKG', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Indonesia', '', 'IDN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Israel', '', 'ISR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'India', '', 'IND', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'British Indian Ocean Territory', '', 'IOT', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Iraq', '', 'IRQ', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Iran', '', 'IRN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Jordan', '', 'JOR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Japan', '', 'JPN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Kyrgyzstan', '', 'KGZ', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Cambodia', '', 'KHM', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'North Korea', '', 'PRK', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'South Korea', '', 'KOR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Kuwait', '', 'KWT', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Kazakhstan', '', 'KAZ', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Laos', '', 'LAO', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Lebanon', '', 'LBN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Sri Lanka', '', 'LKA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Myanmar [Burma]', '', 'MMR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Mongolia', '', 'MNG', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Macau', '', 'MAC', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Maldives', '', 'MDV', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Malaysia', '', 'MYS', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Nepal', '', 'NPL', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Oman', '', 'OMN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Philippines', '', 'PHL', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Pakistan', '', 'PAK', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Palestinian Territories', '', 'PSE', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Qatar', '', 'QAT', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Saudi Arabia', '', 'SAU', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Singapore', '', 'SGP', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Syria', '', 'SYR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Thailand', '', 'THA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Tajikistan', '', 'TJK', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Turkmenistan', '', 'TKM', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Turkey', '', 'TUR', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Taiwan', '', 'TWN', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Uzbekistan', '', 'UZB', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Vietnam', '', 'VNM', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Yemen', '', 'YEM', '');


INSERT INTO GLOBAL_REGION (ID, REGION_TYPE, ENGLISH_NAME) VALUES (null, 'Continent', 'Antartica');
SET @CONTINENT_ID = LAST_INSERT_ID();
	
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Antarctica', '', 'ATA', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Bouvet Island', '', 'BVT', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'South Georgia and the South Sandwich Islands', '', 'SGS', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'Heard Island and McDonald Islands', '', 'HMD', '');
    INSERT INTO GLOBAL_REGION (ID, PARENT_REGION_ID, REGION_TYPE, LOCALIZED_NAME, ENGLISH_NAME, ISO_ALPHA_3_CODE, ISO_ALPHA_2_CODE) VALUES (null, @continentID, 'Country', 'French Southern Territories', '', 'ATF', '');