DROP TABLE IF EXISTS ORGANIZATION;
CREATE TABLE ORGANIZATION(
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ORGANIZATION_CATEGORY_ID BIGINT NOT NULL,
	DENOMINATION_ID BIGINT,
	SUBDENOMINATION_ID BIGINT,
	MUSIC_STYLE VARCHAR(75),
	YEAR_FOUNDED BIGINT,
	SERVICE_TIMES VARCHAR(75),
	SERVICE_DAYS VARCHAR(75),
	NAME VARCHAR(127) NOT NULL,
	PROGRAMS_OFFERED VARCHAR(127) NOT NULL,
	AGE_DEMOGRAPHICS VARCHAR(75) NOT NULL,
	ETHNIC_DEMONGRAPHICS VARCHAR(75) NOT NULL,
	DESCRIPTION VARCHAR(1027) NOT NULL,
	WEBSITE_URL VARCHAR(127) NOT NULL,
	FACEBOOK_URL VARCHAR(127) NOT NULL,
	AVERAGE_SERVICE_CONGREGATION_SIZE BIGINT,
	ENVIRONMENTALLY_FRIENDLY BOOLEAN DEFAULT FALSE
    PARKING_LOT BOOLEAN DEFAULT TRUE,
    GAY_AFIRMING BOOLEAN DEFAULT FALSE,
    PRIMARY_CONTACT_ID BIGINT,
    PRIMARY_LEADER_ID BIGINT,
) engine InnoDB;

DROP TABLE IF EXISTS ORGANIZATION_ADDRESSES;
CREATE TABLE ORGANIZATION_PROFILE_ADDRESSES(
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ADDRESS_ID BIGINT NOT NULL,
    ORGANIZATION_ID BIGINT NOT NULL
) engine InnoDB;

DROP TABLE IF EXISTS ORGANIZATION_LEADERS;
CREATE TABLE ORGANIZATION_LEADERS(
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    LEADER_ID BIGINT NOT NULL,
    ORGANIZATION_ID BIGINT NOT NULL
) engine InnoDB;

DROP TABLE IF EXISTS ORGANIZATION_LANGUAGES;
CREATE TABLE ORGANIZATION_LANGUAGES(
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    LANGUAGE_ID BIGINT NOT NULL,
    ORGANIZATION_ID BIGINT NOT NULL
) engine InnoDB;

DROP TABLE IF EXISTS ORGANIZATION_IMAGES;
CREATE TABLE ORGANIZATION_IMAGES(
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    IMAGE_ID BIGINT NOT NULL,
    ORGANIZATION_ID BIGINT NOT NULL
) engine InnoDB;

DROP TABLE IF EXISTS LEADER;
CREATE TABLE LEADER(
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(31),
	TITLE VARCHAR(31),
	BIO VARCHAR(1027)
	IMAGE_ID BIGINT,
	PRIMARY_CONTACT BOOLEAN,
	PRIMARY_LEADER BOOLEAN,
) engine InnoDB;

